### ISSUE TITLE
Action fails to download

### ISSUE THREAD

**Issue by JoshuaFry** [stefda/action-cloud-run#1]
I've been running into this issue during the setup job process.
```
 build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@1.0.0
``` 

```
[warning]Failed to download action 'https://api.github.com/repos/stefda/action-cloud-run/tarball/1.0'. Error Response status code does not indicate success: 404 (Not Found).
```
